name: Deploy to Remote Machine

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check SERVER_IP
        run: echo "Server IP: $SERVER_IP"
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa $SERVER_IP >> ~/.ssh/known_hosts
      - name: Deploy to Google Cloud VM
